### ISSUE TITLE
Todo list for bun compatibility

### ISSUE THREAD

**Issue by zfben** [faasjs/faasjs#1016]
- [x] [Bun's workflow](https://github.com/faasjs/faasjs/actions/workflows/bun-unit.yml)
- [x] [VS Code image](https://github.com/faasjs/faasjs/blob/main/images/vscode/bun.Dockerfile)
- [x] [Bun image](https://github.com/faasjs/faasjs/tree/main/images/bun)
- [ ] Peer issues: https://github.com/oven-sh/bun/issues/5567, https://github.com/oven-sh/bun/issues/5813
- [ ] Workspace issues: https://github.com/oven-sh/bun/issues/5207
- [ ] Replace jest with bun test
- [ ] Replace http.createServer with bun server
- [ ] Sqlite issue: https://github.com/WiseLibs/better-sqlite3/issues/1034
